### ISSUE TITLE
Problem with updated Power BI template

### ISSUE THREAD

**Issue by ksagala** [MicrosoftDocs/mslearn-organizational-reporting#5]
Looks strange, that no one claimed it earlier, but it seems that pbit file is protected with AIP - when I tried to open it, got an error that file is protected by organization policy. Tried to open on few different computers

**Comment by asajohnson** [comment]
Hi,

Apologies for the delay. This was a bug that got introduced in the last version. It is now resolved and it should work as expected. 

(Note: The [organizational reporting template setup documentation](https://learn.microsoft.com/en-us/training/support/org-reporting-use-power-bi-sqldb-template) also has the corrected link.)

**Comment by ksagala** [comment]
Indeed, now it's possible to import pbit file. I have connected it to database with data being synchronized with older version of report. Still shows few errors but looks properly (orgreporting1.jpg).  I made almost year ago my own version of this. Whole repo is here - https://github.com/ksagala/LearnReporting
![OrgReporting1](https://user-images.githubusercontent.com/22879705/215348762-46667ab7-b9fc-4e9a-aa06-9dc861d1cb16.jpg)
![OrgReporting2](https://user-images.githubusercontent.com/22879705/215348848-ea3bcdc5-56c0-4be4-84cc-d32fbd6405fa.jpg)
